name = "First"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["First"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
linter.style.header.license = "Released under GPL-3.0-only license as described in the file LICENSE."
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "First"
